@extends('layouts.card_image')
@section('transition')
transition-kit
@overwrite
@section('card_width')
1/2
@overwrite
@section('card_title')
WEBSITE
@overwrite
@section('card_caption')
Dinas Kesehatan Sulawesi Tengah
@overwrite
@section('card_url')
https://dinkes.sultengprov.go.id/category/covid-19/
@overwrite
@section('card_image')
https://i.ibb.co/ngd24Rg/dinkes.png
@overwrite
