@extends('layouts.card_image')
@section('transition')
transition-kit
@overwrite
@section('card_width')
1/2
@overwrite
@section('card_title')
WEBSITE
@overwrite
@section('card_caption')
Detexi
@overwrite
@section('card_url')
https://corona.detexi.id/
@overwrite
@section('card_image')
https://i.ibb.co/cFmHfYS/detexi.png
@overwrite
