@extends('layouts.card_image')
@section('transition')
img-bw
@overwrite
@section('card_width')
1/2
@overwrite
@section('card_title')
FRONTEND
@overwrite
@section('card_caption')
Tailwind CSS
@overwrite
@section('card_url')
https://tailwindcss.com
@overwrite
@section('card_image')
https://i.ibb.co/mRmp6d6/tailwind.png
@overwrite
