@extends('layouts.card_image')
@section('transition')
img-bw
@overwrite
@section('card_width')
1/2
@overwrite
@section('card_title')
PROGRAMMING LANGUAGE
@overwrite
@section('card_caption')
PHP
@overwrite
@section('card_url')
https://php.net
@overwrite
@section('card_image')
https://i.ibb.co/ZxHxpVc/lumen.png
@overwrite
