@extends('layouts.card_image')
@section('transition')
img-bw
@overwrite
@section('card_width')
1/2
@overwrite
@section('card_title')
DATABASE
@overwrite
@section('card_caption')
MySQL
@overwrite
@section('card_url')
https://mysql.com
@overwrite
@section('card_image')
https://i.ibb.co/Lv408PG/mysql.png
@overwrite
