@extends('layouts.card_image')
@section('transition')
img-bw
@overwrite
@section('card_width')
1/2
@overwrite
@section('card_title')
DATABASE
@overwrite
@section('card_caption')
Chart JS
@overwrite
@section('card_url')
https://chartjs.org
@overwrite
@section('card_image')
https://i.ibb.co/GFRT6Fm/charts.png
@overwrite
