@extends('layouts.card_image')
@section('transition')
img-bw
@overwrite
@section('card_width')
1/2
@overwrite
@section('card_title')
BACKEND
@overwrite
@section('card_caption')
LUMEN
@overwrite
@section('card_url')
https://lumen.laravel.com
@overwrite
@section('card_image')
https://i.ibb.co/M10wFC0/lumen.png
@overwrite
